---
title: "Teaching"
author: 
output:
  html_document:
    css: "../rekadata.css"
---

Below is a list of the modules and couses which I have developed and taught.

# Current courses

### Making Sense of Criminological Data

10 week 2nd-year Undergraduate introduction to data analysis for BA Criminology and Social Science students at University of Manchester. [See here for more info](https://rekadata.net/teaching/mscd/)

### Designing Criminological Research

This course is for students enrolled in MA, MRes Criminology and MRes Criminology with Social Statistics to teach an introduction to research in topics of Crime, Policing, and Criminal Justice.

# Past courses

### Crime Mapping

Introduction to spatial data analysis and visualisation for criminology students. See course content [here](https://maczokni.github.io/crimemapping_textbook_bookdown/)


# Short courses

### Monash University Masterclass

1-day introduction to data analysis and a gentle intro to R and R Studio using R Studio Cloud. [See here for more info and course websie](https://rekadata.net/teaching/monash_masterclass/). 


### Getting Started in R

One-week introductory course for students to become familiar with data import, wrangling, analysis and visualisation as part of the [methods@manchester](https://www.methods.manchester.ac.uk/connect/events/summer-school-2020/) summer school. See course materials [here](https://rcatlord.github.io/GSinR/)

