---
title: Research
author: ~
date: ''
slug: research
categories: []
tags: []
images: []
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Ongoing Research Projects

## Appeal for Information about Missing Persons

This project, funded by the [Manchester Statistical Society]() is looking at Tweets made by Greater Manchester Police Twitter accounts which are appeals for information about missing persons, in order to determine what features are associated with increased engagement (in the form of retweets) from the public. 

## Using App-Based and Sensing Measures to Map Fear of Crime and Perception of Place

This project, funded by [The British Academy]() explores the feasibility of using mobile applications and physiological sensing in order to measure fear of crime as a situation-specific experience. The first part of the project was to take stock of existing work making use of mobile applications in order to measure fear of crime **in-situ**. The preprint for this paper is available [on Soc ArXiv](). The second part of the paper explores the feasibility of using Galvanic Skin Response and Heart Rate as indicators of fear of crime experienced, and how these correlate with self-report measures and with contextual features measured with eye-tracking. 

## 
